// AUTOMATICALLY GENERATED BY scripts/generate.visitors.js
// @flow

import type Context from '../context';
import t from './babel-types';
import CaseVisitor from '../visitors/Case';
import CodeVisitor from '../visitors/Code';
import ConditionalVisitor from '../visitors/Conditional';
import EachVisitor from '../visitors/Each';
import TagVisitor from '../visitors/Tag';
import TextVisitor from '../visitors/Text';
import WhileVisitor from '../visitors/While';

type Visitor = {
  +jsx?: (node: Object, context: Context) => JSXValue,
  +expression: (node: Object, context: Context) => Expression,
};

const visitors = {
  Case: (CaseVisitor: Visitor),
  Code: (CodeVisitor: Visitor),
  Conditional: (ConditionalVisitor: Visitor),
  Each: (EachVisitor: Visitor),
  Tag: (TagVisitor: Visitor),
  Text: (TextVisitor: Visitor),
  While: (WhileVisitor: Visitor),
};
export default visitors;
