// flow-typed signature: 3d55f3b05ef5bd4e9742c6b4ba529e64
// flow-typed version: <<STUB>>/babel-preset-forbeslindesay_v^2.1.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-forbeslindesay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-forbeslindesay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-forbeslindesay/index' {
  declare module.exports: $Exports<'babel-preset-forbeslindesay'>;
}
declare module 'babel-preset-forbeslindesay/index.js' {
  declare module.exports: $Exports<'babel-preset-forbeslindesay'>;
}
