// flow-typed signature: 0aa1e9f97d82d1d9ebcb054520ebb9be
// flow-typed version: <<STUB>>/eslint-config-forbeslindesay_v^1.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-forbeslindesay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-forbeslindesay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-forbeslindesay/index' {
  declare module.exports: $Exports<'eslint-config-forbeslindesay'>;
}
declare module 'eslint-config-forbeslindesay/index.js' {
  declare module.exports: $Exports<'eslint-config-forbeslindesay'>;
}
