// flow-typed signature: ce1b54c961442e29b516a76f5968e368
// flow-typed version: <<STUB>>/pug-error_v^1.3.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pug-error'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pug-error' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'pug-error/index' {
  declare module.exports: $Exports<'pug-error'>;
}
declare module 'pug-error/index.js' {
  declare module.exports: $Exports<'pug-error'>;
}
