// flow-typed signature: 49455e97a77717c4c77712142cce85c1
// flow-typed version: <<STUB>>/pug-filters_v^2.1.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pug-filters'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pug-filters' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pug-filters/lib/handle-filters' {
  declare module.exports: any;
}

declare module 'pug-filters/lib/run-filter' {
  declare module.exports: any;
}

declare module 'pug-filters/test/custom-filters' {
  declare module.exports: any;
}

declare module 'pug-filters/test/filter-aliases.test' {
  declare module.exports: any;
}

declare module 'pug-filters/test/index.test' {
  declare module.exports: any;
}

declare module 'pug-filters/test/per-filter-options-applied-to-nested-filters.test' {
  declare module.exports: any;
}

declare module 'pug-filters/test/update-test-cases' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pug-filters/index' {
  declare module.exports: $Exports<'pug-filters'>;
}
declare module 'pug-filters/index.js' {
  declare module.exports: $Exports<'pug-filters'>;
}
declare module 'pug-filters/lib/handle-filters.js' {
  declare module.exports: $Exports<'pug-filters/lib/handle-filters'>;
}
declare module 'pug-filters/lib/run-filter.js' {
  declare module.exports: $Exports<'pug-filters/lib/run-filter'>;
}
declare module 'pug-filters/test/custom-filters.js' {
  declare module.exports: $Exports<'pug-filters/test/custom-filters'>;
}
declare module 'pug-filters/test/filter-aliases.test.js' {
  declare module.exports: $Exports<'pug-filters/test/filter-aliases.test'>;
}
declare module 'pug-filters/test/index.test.js' {
  declare module.exports: $Exports<'pug-filters/test/index.test'>;
}
declare module 'pug-filters/test/per-filter-options-applied-to-nested-filters.test.js' {
  declare module.exports: $Exports<'pug-filters/test/per-filter-options-applied-to-nested-filters.test'>;
}
declare module 'pug-filters/test/update-test-cases.js' {
  declare module.exports: $Exports<'pug-filters/test/update-test-cases'>;
}
