// flow-typed signature: 25d208f5dc0309ece8dc1524005b2527
// flow-typed version: <<STUB>>/pug-strip-comments_v1.0.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pug-strip-comments'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pug-strip-comments' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pug-strip-comments/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pug-strip-comments/index' {
  declare module.exports: $Exports<'pug-strip-comments'>;
}
declare module 'pug-strip-comments/index.js' {
  declare module.exports: $Exports<'pug-strip-comments'>;
}
declare module 'pug-strip-comments/test/index.test.js' {
  declare module.exports: $Exports<'pug-strip-comments/test/index.test'>;
}
