// flow-typed signature: 9fced7a31538b943ca1adea432efe916
// flow-typed version: <<STUB>>/pug-parser_v^2.0.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pug-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pug-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pug-parser/lib/inline-tags' {
  declare module.exports: any;
}

declare module 'pug-parser/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pug-parser/index' {
  declare module.exports: $Exports<'pug-parser'>;
}
declare module 'pug-parser/index.js' {
  declare module.exports: $Exports<'pug-parser'>;
}
declare module 'pug-parser/lib/inline-tags.js' {
  declare module.exports: $Exports<'pug-parser/lib/inline-tags'>;
}
declare module 'pug-parser/test/index.test.js' {
  declare module.exports: $Exports<'pug-parser/test/index.test'>;
}
