// flow-typed signature: e36f7e6753cb6e6ef94bbdf7f1727022
// flow-typed version: <<STUB>>/pug-lexer_v^3.1.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pug-lexer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pug-lexer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pug-lexer/test/cases/javascript-new-lines' {
  declare module.exports: any;
}

declare module 'pug-lexer/test/check-lexer-functions.test' {
  declare module.exports: any;
}

declare module 'pug-lexer/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pug-lexer/index' {
  declare module.exports: $Exports<'pug-lexer'>;
}
declare module 'pug-lexer/index.js' {
  declare module.exports: $Exports<'pug-lexer'>;
}
declare module 'pug-lexer/test/cases/javascript-new-lines.js' {
  declare module.exports: $Exports<'pug-lexer/test/cases/javascript-new-lines'>;
}
declare module 'pug-lexer/test/check-lexer-functions.test.js' {
  declare module.exports: $Exports<'pug-lexer/test/check-lexer-functions.test'>;
}
declare module 'pug-lexer/test/index.test.js' {
  declare module.exports: $Exports<'pug-lexer/test/index.test'>;
}
